---
- name: Update JAVA_HOME
  lineinfile:
    path: "{{ hadoop_dir }}/etc/hadoop/hadoop-env.sh"
    insertafter: EOF
    line: "{{ item }}"
  loop:
    - export YARN_RESOURCEMANAGER_USER="root"
    - export YARN_NODEMANAGER_USER="root"

- copy:
    dest: "{{ hadoop_dir }}/etc/hadoop/mapred-site.xml"
    content: |
      <?xml version="1.0"?>
      <configuration>
          <property>
              <name>mapreduce.framework.name</name>
              <value>yarn</value>
          </property>
          <property>
              <name>mapreduce.application.classpath</name>
              <value>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*:$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*</value>
          </property>
      </configuration>    
  notify: reload hadoop yarn

- copy:
    dest: "{{ hadoop_dir }}/etc/hadoop/yarn-site.xml"
    content: |
      <?xml version="1.0"?>
      <configuration>
          <property>
              <name>yarn.nodemanager.aux-services</name>
              <value>mapreduce_shuffle</value>
          </property>
          <property>
              <name>yarn.nodemanager.env-whitelist</name>
              <value>JAVA_HOME,HADOOP_COMMON_HOME,HADOOP_HDFS_HOME,HADOOP_CONF_DIR,CLASSPATH_PREPEND_DISTCACHE,HADOOP_YARN_HOME,HADOOP_MAPRED_HOME</value>
          </property>
      </configuration>
  notify: reload hadoop yarn
